### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by cheeyi** [cheeyi/cheeyi.github.io#1]
The blog repo is now publicly available since my student developer pack for GitHub (which allows me to make an unlimited number of private repos) is expiring 😢 

### To-dos
- [ ] Update logo (waiting on design)
- [ ] Remove redundant files
- [ ] Replace copyrighted images with my own
- [ ] Squash all set up into 1 commit

**Comment by cheeyi** [comment]
Moved to using Jekyll.
